### ISSUE TITLE
Tutorial 1 shrink step explodes -- Seed RNGs?

### ISSUE THREAD

**Issue by RainierBarrett** [cmelab/hoomd-organics#41] opened 2023-09-11 17:32 UTC
Reviewing the [tutorials PR](https://github.com/cmelab/hoomd-organics/pull/38), I had a box explode in the shrink step:

```Step 0 of 1000; TPS: 0.0; ETA: inf minutes
Step 100 of 1000; TPS: 169.02; ETA: 0.1 minutes
Step 200 of 1000; TPS: 165.75; ETA: 0.1 minutes
Step 300 of 1000; TPS: 161.35; ETA: 0.1 minutes
Step 400 of 1000; TPS: 155.2; ETA: 0.1 minutes
Step 500 of 1000; TPS: 149.97; ETA: 0.1 minutes
Step 600 of 1000; TPS: 143.11; ETA: 0.0 minutes
Step 700 of 1000; TPS: 134.37; ETA: 0.0 minutes
Step 800 of 1000; TPS: 121.35; ETA: 0.0 minutes

**ERROR**: Particle with unique tag 492 is no longer in the simulation box.

Cartesian coordinates: 
x: 27.5192 y: 75.981 z: -99.5512
Fractional coordinates: 
f.x: 4.78958 f.y: 12.3436 f.z: -15.0177
Local box lo: (-3.20768, -3.20768, -3.20768)
          hi: (3.20768, 3.20768, 3.20768)

Step 900 of 1000; TPS: 97.58; ETA: 0.0 minutes

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[14], line 1
----> 1 sim.run_update_volume(n_steps=1000, period=1, kT=1, tau_kt=1, final_box_lengths=system.target_box)

File ~/repos/hoomd-organics/hoomd_organics/base/simulation.py:442, in Simulation.run_update_volume(self, n_steps, period, kT, tau_kt, final_box_lengths, thermalize_particles)
    437 std_out_logger_printer = hoomd.update.CustomUpdater(
    438     trigger=hoomd.trigger.Periodic(self._std_out_freq),
    439     action=std_out_logger,
    440 )
    441 self.operations.updaters.append(std_out_logger_printer)
--> 442 self.run(n_steps + 1)
    443 self.operations.updaters.remove(std_out_logger_printer)

File ~/anaconda3/envs/hoomd-organics-dev/lib/python3.9/site-packages/hoomd/simulation.py:462, in Simulation.run(self, steps, write_at_start)
    458 if steps_int < 0 or steps_int > TIMESTEP_MAX - 1:
    459     raise ValueError(f"steps must be in the range [0, "
    460                      f"{TIMESTEP_MAX-1}]")
--> 462 self._cpp_sys.run(steps_int, write_at_start)

RuntimeError: Error computing cell list

```

Not sure if this is a fluke or not, but regardless, I think we should seed the HOOMD random number generation for the tutorials to make sure everyone who reads them sees the same thing.

**Comment by chrisjonesBSU** [comment] 2023-09-11 17:34
Did you see the comments I left in #38 and try running it with those changes?  I was able to run through the shrinking step, plus an additional NVT step. I doubt the issue is due to us using different random seeds (but I don't disagree that we should set the seed values in the tutorial anyway).

**Comment by marjanAlbouye** [comment] 2023-09-11 17:35
The Simulation class uses the default seed=42 for every simulation. The seed can be configured by the user too.

**Comment by RainierBarrett** [comment] 2023-09-11 17:54
Ah, missed those comments, thanks Chris. As for the default seed, that's good, but in that case I think we should mention that explicitly in case folks want to change it.

**Comment by chrisjonesBSU** [comment] 2023-09-13 17:27
Closing as I think we figured out the issue.

**Closed by chrisjonesBSU** 2023-09-13 17:27 UTC
